dist: trusty

language: python

notifications:
  email: false

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - gcc
    - libhdf5-8
    - libhdf5-serial-dev
    - libblas-dev
    - liblapack-dev
    - libatlas-dev
    - libatlas-base-dev
    - libquadmath0

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

# command to install dependencies
#
# Seem to need unittest2 on Python 2.6.
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install -r requirements.txt

# command to run tests
script: nosetests -I='*compatibility*'
