dist: trusty

language: python

notifications:
  email: false

addons:
  apt:
    packages:
    - gcc
    - libhdf5-serial-dev
    - libblas-dev
    - liblapack-dev
    - libatlas-dev
    - libatlas-base-dev
    - libquadmath0

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

# command to install dependencies
#
# Seem to need unittest2 on Python 2.6 as well as Numpy 1.9 or newer
# on Python 2.
#
# Testing an older version of h5py and cython to determine errors.
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install Cython==0.22
  - pip install -U numpy
  - pip install h5py==2.4
  - pip install -r requirements.txt

# command to run tests
script: nosetests -I='*compatibility*'