sudo: required

dist: trusty

language: python

notifications:
  email: false

addons:
  apt:
    packages:
    - gcc
    - libhdf5-serial-dev
    - python-scipy
    - python3-scipy

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install -r requirements.txt

# command to run tests
script: nosetests -I='*compatibility*'