dist: xenial
sudo: required

language: python

notifications:
  email: false

env:
  - H5PY_VER="==2.5"
  - H5PY_VER="==2.6"
  - H5PY_VER="==2.7"
  - H5PY_VER="==2.8"
  - H5PY_VER="==2.9"
  - H5PY_VER=""

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc libhdf5-serial-dev libblas-dev liblapack-dev libatlas-dev libatlas-base-dev libquadmath0

# command to install dependencies
install:
  - pip install -U numpy Cython
  - pip install h5py$H5PY_VER
  - pip install -r requirements_tests.txt

# command to run tests
script: nosetests
