sudo: required

dist: trusty

language: python

notifications:
  email: false

addons:
  apt:
    packages:
    - gcc
    - libhdf5-serial-dev
    - python-scipy
    - python3-scipy

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

# command to install dependencies
#
# Seem to need unittest2 on Python 2.6 as well as Numpy 1.8 or newer
# on Python 2.
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - if [[ 'True' == `python -c 'from __future__ import print_function; from distutils.version import LooseVersion; import numpy; print(LooseVersion(numpy.__version__) < LooseVersion("1.8"))'`]]; then pip uninstall numpy; pip install numpy==1.8.2; fi
  - pip install -r requirements.txt

# command to run tests
script: nosetests -I='*compatibility*'